// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1jiMBt7MBs6jsQbJIQ9TN53I2FAfVHu4',
    appId: '1:70871339363:web:60d72d5fb79da40bdb0356',
    messagingSenderId: '70871339363',
    projectId: 'aaaaa-e52c4',
    authDomain: 'aaaaa-e52c4.firebaseapp.com',
    databaseURL: 'https://aaaaa-e52c4.firebaseio.com',
    storageBucket: 'aaaaa-e52c4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrMrVsmNohLrDPMXotjMnEVbzf6t01QKk',
    appId: '1:70871339363:android:075cc4e60d159a1fdb0356',
    messagingSenderId: '70871339363',
    projectId: 'aaaaa-e52c4',
    databaseURL: 'https://aaaaa-e52c4.firebaseio.com',
    storageBucket: 'aaaaa-e52c4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPHwfGsyKxp_oDJCxG0pClYn0iGXqFMqw',
    appId: '1:70871339363:ios:57204049c1d8d31adb0356',
    messagingSenderId: '70871339363',
    projectId: 'aaaaa-e52c4',
    databaseURL: 'https://aaaaa-e52c4.firebaseio.com',
    storageBucket: 'aaaaa-e52c4.appspot.com',
    iosBundleId: 'com.siyuwen.qim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPHwfGsyKxp_oDJCxG0pClYn0iGXqFMqw',
    appId: '1:70871339363:ios:9be021533277bf39db0356',
    messagingSenderId: '70871339363',
    projectId: 'aaaaa-e52c4',
    databaseURL: 'https://aaaaa-e52c4.firebaseio.com',
    storageBucket: 'aaaaa-e52c4.appspot.com',
    iosBundleId: 'com.example.qim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB1jiMBt7MBs6jsQbJIQ9TN53I2FAfVHu4',
    appId: '1:70871339363:web:2643f4be878be169db0356',
    messagingSenderId: '70871339363',
    projectId: 'aaaaa-e52c4',
    authDomain: 'aaaaa-e52c4.firebaseapp.com',
    databaseURL: 'https://aaaaa-e52c4.firebaseio.com',
    storageBucket: 'aaaaa-e52c4.appspot.com',
  );
}
