// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgmKSIIyveGrQACeWXEe1hq_NY44beY4Y',
    appId: '1:822705825488:web:2d22679e38c00ef298a0d5',
    messagingSenderId: '822705825488',
    projectId: 'messagesend-e0b2d',
    authDomain: 'messagesend-e0b2d.firebaseapp.com',
    storageBucket: 'messagesend-e0b2d.appspot.com',
    measurementId: 'G-12QQQSZXPV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzQ7bJcej-PpjPEyfIDhmKmukG3L6m-a8',
    appId: '1:822705825488:android:1d2de3c129b1faa498a0d5',
    messagingSenderId: '822705825488',
    projectId: 'messagesend-e0b2d',
    storageBucket: 'messagesend-e0b2d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlQBeZ-SoyaFukUHh56c5Hk2hgy35CaRU',
    appId: '1:822705825488:ios:4de5ad5c24374fb398a0d5',
    messagingSenderId: '822705825488',
    projectId: 'messagesend-e0b2d',
    storageBucket: 'messagesend-e0b2d.appspot.com',
    androidClientId: '822705825488-g08u9ahu55q1nts47iov7rfggi4bsd2q.apps.googleusercontent.com',
    iosClientId: '822705825488-skjuekp8hmtv3atv2ep07kp386n18cle.apps.googleusercontent.com',
    iosBundleId: 'com.siyuwen.qim',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlQBeZ-SoyaFukUHh56c5Hk2hgy35CaRU',
    appId: '1:822705825488:ios:05a18958ee80dc5498a0d5',
    messagingSenderId: '822705825488',
    projectId: 'messagesend-e0b2d',
    storageBucket: 'messagesend-e0b2d.appspot.com',
    androidClientId: '822705825488-g08u9ahu55q1nts47iov7rfggi4bsd2q.apps.googleusercontent.com',
    iosBundleId: 'com.example.qim',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgmKSIIyveGrQACeWXEe1hq_NY44beY4Y',
    appId: '1:822705825488:web:d7a162ff59c0e79998a0d5',
    messagingSenderId: '822705825488',
    projectId: 'messagesend-e0b2d',
    authDomain: 'messagesend-e0b2d.firebaseapp.com',
    storageBucket: 'messagesend-e0b2d.appspot.com',
    measurementId: 'G-BF1MQM292T',
  );

}